name: PHP Lint

on: [push]

jobs:
  PHPCS:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install --no-scripts --dev --prefer-dist --no-progress --no-suggest
          composer require --no-scripts --dev staabm/annotate-pull-request-from-checkstyle
      - name: Run phpcs
        run: ./vendor/bin/phpcs -q --report=checkstyle | ./vendor/bin/cs2pr --graceful-warnings
